# Read the Docs configuration file
version: 2

# Set the OS and Python version
build:
  os: ubuntu-24.04
  tools:
    python: "3.11"   # שים לב לשינוי לגרסה נתמכת

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Install Python dependencies
python:
  install:
    - requirements: requirements.txt
